#SPDX-License-Identifier: Apache-2.0
galaxy_info:
  role_name: cluster_installation_check
  author: Red Hat Consulting Services
  description: A role to bootstrap an OpenShift cluster
  company: Red Hat

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://github.com/redhat-consulting-services/ansible-collection-openshift/issues

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: Apache-2.0

  min_ansible_version: "2.18"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - openshift
    - ocp
    - k8s
    - kubernetes
    - nodes
    - health check
    - health
    - check
    - status
    - cluster status
    - ansible
    - automation

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
