generate_iso: true
iso_type: "iso"

pull_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256

ssh_public_key: |
  ssh-ed25519 AAAAAAA... openshift@machines.ocp.example.com

additional_ntp_sources:
  - 192.168.255.100
  - 192.168.255.101

api_vip: 10.10.10.8
ingress_vip: 10.10.10.9

proxy:
  http: http://10.10.9.11:9148
  https: http://10.10.9.111:9148
  no_proxy: "localhost,ocp.example.com,apps.ocp.example.com,10.10.10.0/24"

networking:
  cluster_networks:
    - cidr: "10.172.0.0/14"
      host_prefix: 22
  service_networks:
    - 10.171.0.0/16
  network_type: "OVNKubernetes"
  machine_network:
    - cidr: 10.10.10.0/24

agent_config:
  master:
    root_device_name: "/dev/sda"
    dns_resolvers: &dns_resolvers
      - 192.168.254.11
      - 192.168.254.12
    routes: &routes
      - destination: 0.0.0.0/0
        gateway: 10.10.10.1
        interface: bond0.1111
        table_id: 254
    bonds: &bonds
      - name: bond0
        # lacp bond
        mode: "802.3ad"
        options:
          miimon: "140"
    vlans: &vlans
      - name: bond0.1111
        id: 1111
        base_interface: bond0
    hosts:
      - hostname: master-01.ocp.example.com
        root_device:
          serial_number: "0000000000000001"
        interfaces:
          - name: eth0
            mac_address: "00:01:00:00:00:01"
            part_of_bond: "bond0"
            mtu: 1500
          - name: eth1
            mac_address: "00:01:00:00:00:02"
            part_of_bond: "bond0"
            mtu: 1500
        vlans:
          - interface: bond0.1111
            addresses:
              - ip: 10.10.10.10
                subnet_length: 24

      - hostname: master-02.ocp.example.com
        root_device:
          serial_number: "0000000000000002"
        interfaces:
          - name: eth0
            mac_address: "00:01:00:00:01:01"
            part_of_bond: "bond0"
            mtu: 1500
          - name: eth1
            mac_address: "00:01:00:00:01:02"
            part_of_bond: "bond0"
            mtu: 1500
        vlans:
          - interface: bond0.1111
            addresses:
              - ip: 10.10.10.11
                subnet_length: 24

      - hostname: master-03.ocp.example.com
        root_device:
          serial_number: "0000000000000003"
        interfaces:
          - name: eth0
            mac_address: "00:01:00:00:02:01"
            part_of_bond: "bond0"
            mtu: 1500
          - name: eth1
            mac_address: "00:01:00:00:02:02"
            part_of_bond: "bond0"
            mtu: 1500
        vlans:
          - interface: bond0.1111
            addresses:
              - ip: 10.10.10.12
                subnet_length: 24

  worker:
    root_device_name: "/dev/sda"
    dns_resolvers: *dns_resolvers
    routes: *routes
    bonds: *bonds
    vlans: *vlans
    hosts:
      - hostname: infra-01.ocp.example.com
        root_device:
          serial_number: "0000010000000001"
        interfaces:
          - name: eth0
            mac_address: "00:02:00:00:00:01"
            part_of_bond: "bond0"
            mtu: 1500
          - name: eth1
            mac_address: "00:02:00:00:00:02"
            part_of_bond: "bond0"
            mtu: 1500
        vlans:
          - interface: bond0.1111
            addresses:
              - ip: 10.10.10.20
                subnet_length: 24

      - hostname: infra-02.ocp.example.com
        root_device:
          serial_number: "0000010000000002"
        interfaces:
          - name: eth0
            mac_address: "00:02:00:00:01:01"
            part_of_bond: "bond0"
            mtu: 1500
          - name: eth1
            mac_address: "00:02:00:00:01:02"
            part_of_bond: "bond0"
            mtu: 1500
        vlans:
          - interface: bond0.1111
            addresses:
              - ip: 10.10.10.21
                subnet_length: 24

      - hostname: infra-03.ocp.example.com
        root_device:
          serial_number: "0000010000000003"
        interfaces:
          - name: eth0
            mac_address: "00:02:00:00:02:01"
            part_of_bond: "bond0"
            mtu: 1500
          - name: eth1
            mac_address: "00:02:00:00:02:02"
            part_of_bond: "bond0"
            mtu: 1500
        vlans:
          - interface: bond0.1111
            addresses:
              - ip: 10.10.10.22
                subnet_length: 24
