cpu_architecture: amd64
kubeconfig_path: "~/.kube/config"
generate_iso: false
base_dir: "/iso"
pull_secret: ""
worker:
  root_device_name: "/dev/sda"
  bonds: []
  bridges: []
  vlans: []
  hosts: []
